### PR TITLE
Danish translations

### PR DESCRIPTION
**Pull request by MikkelHebel**
I'm a native danish speaker and I have translated all of the messages of pelican into danish.
Contact me if there's any mistakes or questions.

### CODE REVIEW

**Comment by MikkelHebel** [comment]
> Translation are on Crowdin: https://crowdin.com/project/pelican-dev

I made my translations before the crowdin thing was setup.

**Comment by gOOvER** [comment]
> > Translation are on Crowdin: https://crowdin.com/project/pelican-dev
> 
> I made my translations before the crowdin thing was setup.

then i think, you must upload the files there. Should not be hard. There is an option

**Comment by MikkelHebel** [comment]
> I have read the CLA Document and I hereby sign the CLA

> > > Translation are on Crowdin: https://crowdin.com/project/pelican-dev
> > 
> > 
> > I made my translations before the crowdin thing was setup.
> 
> then i think, you must upload the files there. Should not be hard. There is an option

Will that still count towards my GitHub contributions?

**Comment by gOOvER** [comment]
> > I have read the CLA Document and I hereby sign the CLA
> 
> > > > Translation are on Crowdin: https://crowdin.com/project/pelican-dev
> > > 
> > > 
> > > I made my translations before the crowdin thing was setup.
> > 
> > 
> > then i think, you must upload the files there. Should not be hard. There is an option
> 
> Will that still count towards my GitHub contributions?

not on Github

**Comment by MikkelHebel** [comment]
> > > I have read the CLA Document and I hereby sign the CLA
> > 
> > 
> > > > > Translation are on Crowdin: https://crowdin.com/project/pelican-dev
> > > > 
> > > > 
> > > > I made my translations before the crowdin thing was setup.
> > > 
> > > 
> > > then i think, you must upload the files there. Should not be hard. There is an option
> > 
> > 
> > Will that still count towards my GitHub contributions?
> 
> not on Github

Then I'm not interested in redoing my work on crowdin.

**Comment by MikkelHebel** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by gOOvER** [comment]
> > > > I have read the CLA Document and I hereby sign the CLA
> > > 
> > > 
> > > > > > Translation are on Crowdin: https://crowdin.com/project/pelican-dev
> > > > > 
> > > > > 
> > > > > I made my translations before the crowdin thing was setup.
> > > > 
> > > > 
> > > > then i think, you must upload the files there. Should not be hard. There is an option
> > > 
> > > 
> > > Will that still count towards my GitHub contributions?
> > 
> > 
> > not on Github
> 
> Then I'm not interested in redoing my work on crowdin.

normally no need for this. You should able upload your translations to crowdin

**Comment by MikkelHebel** [comment]
> > > > > I have read the CLA Document and I hereby sign the CLA
> > > > 
> > > > 
> > > > > > > Translation are on Crowdin: https://crowdin.com/project/pelican-dev
> > > > > > 
> > > > > > 
> > > > > > I made my translations before the crowdin thing was setup.
> > > > > 
> > > > > 
> > > > > then i think, you must upload the files there. Should not be hard. There is an option
> > > > 
> > > > 
> > > > Will that still count towards my GitHub contributions?
> > > 
> > > 
> > > not on Github
> > 
> > 
> > Then I'm not interested in redoing my work on crowdin.
> 
> normally no need for this. You should able upload your translations to crowdin

Yeah but I started translations before the Crowdin thing, and I want GitHub contribution points since I already did the work D: xd

**Comment by gOOvER** [comment]
> 
> Yeah but I started translations before the Crowdin thing, and I want GitHub contribution points since I already did the work D: xd

sounds bad now, but its not so easy after crowdin is added to a repo. Upload your files to crowdin. I think, it the only way you have, becasue Crowdin manage now the full translations and do not add translations, where added to main repo.

**Comment by notAreYouScared** [comment]
Thankyou for uploading them to Crowdin

**Pull request closed without merging**
