### PR TITLE
Improve Mobile Experience 

### PR DESCRIPTION
**Pull request by notAreYouScared**
Hides text columns here and there, proper grid here and there.

### CODE REVIEW

**Comment by NaysKutzu** [comment]
But why?

**Comment by notAreYouScared** [comment]
> But why?

Not sure what you're referring to?

**Comment by NaysKutzu** [comment]
> > But why?
> 
> Not sure what you're referring to?

Why improve it?
It looks cool like it is because I tried it.

**Comment by notAreYouScared** [comment]
image-12

This looks good for you? ....

**Comment by NaysKutzu** [comment]
I mean on my phone it does not look like that

**Comment by NaysKutzu** [comment]
Okay well you were right did not check the node creation page 
https://mythical.pics/i?i=1713364452

**Pull request merged**
