### PR TITLE
Add artisan command for setting up redis

### PR DESCRIPTION
**Pull request by Boy132**
Instead of having to run 3 commands (with the same input multiple times) you can simply run this one command.

### CODE REVIEW

**Comment by RMartinOscar** [comment]
Shouldn't we remove those then as we can only have one redis cache instance ?
https://github.com/pelican-dev/panel/blob/fc643f57f9c2d862fc0d3644ca98945a1afcd599/app/Console/Commands/Environment/CacheSettingsCommand.php#L25-L28
https://github.com/pelican-dev/panel/blob/fc643f57f9c2d862fc0d3644ca98945a1afcd599/app/Console/Commands/Environment/QueueSettingsCommand.php#L25-L28
https://github.com/pelican-dev/panel/blob/fc643f57f9c2d862fc0d3644ca98945a1afcd599/app/Console/Commands/Environment/SessionSettingsCommand.php#L26-L29

**Comment by Boy132** [comment]
> Shouldn't we remove those then as we can only have one redis cache instance ?
> 
> https://github.com/pelican-dev/panel/blob/fc643f57f9c2d862fc0d3644ca98945a1afcd599/app/Console/Commands/Environment/CacheSettingsCommand.php#L25-L28
> 
> 
> https://github.com/pelican-dev/panel/blob/fc643f57f9c2d862fc0d3644ca98945a1afcd599/app/Console/Commands/Environment/QueueSettingsCommand.php#L25-L28
> 
> 
> https://github.com/pelican-dev/panel/blob/fc643f57f9c2d862fc0d3644ca98945a1afcd599/app/Console/Commands/Environment/SessionSettingsCommand.php#L26-L29

No, you still should be able to run the other commands, e.g. if you only want to use redis for one thing.

**Comment by RMartinOscar** [comment]
> No, you still should be able to run the other commands, e.g. if you only want to use redis for one thing.

Can't you just change --driver ?
https://github.com/pelican-dev/panel/blob/fc643f57f9c2d862fc0d3644ca98945a1afcd599/app/Console/Commands/Environment/CacheSettingsCommand.php#L24

**Comment by RMartinOscar** [comment]
> No, you still should be able to run the other commands, e.g. if you only want to use redis for one thing.
You first do `php artisan p:redis:setup` then you set Cache, Queue and/or Session so you just have to specify the driver not redis user,pass,host for each of them

So you can have Cache and Queue as redis and Session as file/db for some reason.
But you don't have to enter --redis-user --redis-pass --redis-host every single time you want to set one to use redis

**Comment by Boy132** [comment]
> > No, you still should be able to run the other commands, e.g. if you only want to use redis for one thing.
> > You first do `php artisan p:redis:setup` then you set Cache, Queue and/or Session so you just have to specify the driver not redis user,pass,host for each of them
> 
> So you can have Cache and Queue as redis and Session as file/db for some reason. But you don't have to enter --redis-user --redis-pass --redis-host every single time you want to set one to use redis

In that case you can either run the new command and change the session driver later back or use only the cache & queue driver commands to change it to redis. That's the point of this new command - to simply the process of setting multiple drivers to redis at once.

**Review by lancepioch — APPROVED** [review]

**Pull request merged**
