### PR TITLE
Add DatabaseHost alias

### PR DESCRIPTION
**Pull request by RMartinOscar**
Add alias to DatabaseHosts and display that instead of the ip in the endpoint.
Useful when you create pelicanuser@127.0.0.1 but still want to show either a domain or for example 172.18.0.1
List
Edit
Create
Client side eye
Client side list

### CODE REVIEW

**Comment by lancepioch** [comment]
Sorry I don't get what this solves. You should be able to use the domain in the host column and the name is the "alias"

**Comment by Boy132** [comment]
> Sorry I don't get what this solves. You should be able to use the domain in the host column and the name is the "alias"

It's for users that use a local ip or `localhost` for the host but want to show a different value.

**Comment by notAreYouScared** [comment]
> > Sorry I don't get what this solves. You should be able to use the domain in the host column and the name is the "alias"
> 
> It's for users that use a local ip or `localhost` for the host but want to show a different value.

We have a 'Display Name' section. The admin could just put `db.pelican.dev` and that would be displayed to the end-user on the connection details. Unless that's broken?

**Comment by RMartinOscar** [comment]
> We have a 'Display Name' section. The admin could just put `db.pelican.dev` and that would be displayed to the end-user on the connection details. Unless that's broken?

The Display name is only for the admin side its not passed to react and never was

**Review by Boy132 — CHANGES_REQUESTED** [review]
Like Charles said the `Display Name` is supposed to be used as an alias.
Could change the PR to fix that? Thanks.

**Comment by RMartinOscar** [comment]
> Like Charles said the `Display Name` is supposed to be used as an alias. Could change the PR to fix that? Thanks.

That means i'd have to edit the old client part is it worth doing ?

**Comment by Boy132** [comment]
> > Like Charles said the `Display Name` is supposed to be used as an alias. Could change the PR to fix that? Thanks.
> 
> I thought it was just a name on the admin side kinda like for Nodes That means i'd have to edit the old client part is it worth doing or should i wait and reimplement it after [#353](https://github.com/pelican-dev/panel/issues/353) ?

You can do it now, it's just a small edit. #353 will take a while.

**Comment by RMartinOscar** [comment]
I was looking for issues to solve on Pterodactyl's git and i stumbled upon [this one](https://github.com/pterodactyl/panel/issues/5096) that made me unsure about the solution, should i follow what was previously said or implement it differently to comply with that issue aswell ?

**Comment by lancepioch** [comment]
After reading the original issue, I think it has some merit, however I think we should think more carefully about the execution. Let's continue this in a repo discussion!

**Pull request closed without merging**
