### PR TITLE
More Translation and a few changes

### PR DESCRIPTION
**Pull request by Poseidon281**
What i will be translating this PR:

app/Filament/Resources

Now Translated:

app/Filament/Resources/UserResource/Pages

Currently Working on:

app/Filament/Resources/ServerResource/Pages

Sorry for the 3 PR's, but there was something weird going on with the first 2 which caused them to have commits that i did not add as you can see

#180 
#181 

This one does not have those commits only the ones i did

### CODE REVIEW

**Comment by iamkubi** [comment]
recheck

**Comment by iamkubi** [comment]
Ignore the CLA bot.  It's misbehaving, I think.

**Comment by Poseidon281** [comment]
recheck

**Comment by lancepioch** [comment]
We're gonna hold off on translations for a hot bit so we can organize them.

**Pull request closed without merging**
