### PR TITLE
Custom error pages

### PR DESCRIPTION
**Pull request by Boy132**
Adds (simple) custom error pages for 401, 403, 404, 418, 500 and 503 in a more filament-ish style.

grafik
grafik
grafik

### CODE REVIEW

**Comment by JustRed23** [comment]
No 418 error support :(

**Comment by Boy132** [comment]
> No 418 error support :(

Fixed. :)
grafik

**Comment by QuintenQVD0** [comment]
@Boy132 Working / trying to fix the 500 on opening files that do not exsit.

with this PR and the wings returning 404
afbeelding

We still get this:
afbeelding

And not the acutal 404 page

**Comment by Boy132** [comment]
> @Boy132 Working / trying to fix the 500 on opening files that do not exsit.
> 
> with this PR and the wings returning 404 afbeelding
> 
> We still get this: afbeelding
> 
> And not the acutal 404 page

Yes, that's correct. The panel still needs to handle the 404 correctly.
This PR is just a visual update for the error pages, no changed functionality.

**Review by notAreYouScared — APPROVED** [review]

**Comment by notAreYouScared** [comment]
Pray for dark mode <3

**Review by lancepioch — APPROVED** [review]

**Comment by Boy132** [comment]
> Pray for dark mode <3

image

**Pull request merged**
