### PR TITLE
Default to 8443 if https

### PR DESCRIPTION
**Pull request by RMartinOscar**

### CODE REVIEW

**Comment by Boy132** [comment]
Why? There is no reason to _always_ default to `8443` if using https.

**Comment by RMartinOscar** [comment]
Feels wrong to server https over a http port; Maybe i should set it to 4443 instead of 8443 even 🤔

**Comment by Boy132** [comment]
8080 is not a http port per se. Just with cloudflare.

**Comment by RMartinOscar** [comment]
> 8080 is not a http port per se. Just with cloudflare.

So you would serve https over 81 without thinking about it ?

**Comment by Boy132** [comment]
> > 8080 is not a http port per se. Just with cloudflare.
> 
> So you would serve https over 81 without thinking about it ?

Wings doesn't care about the port. 81 would work with https, 444 with http.
As long as there is no software limitation it makes no sense to have two default ports. That just adds necessary complexity.

**Pull request closed without merging**
