### PR TITLE
feat: Replace Yarn with Pnpm

### PR DESCRIPTION
**Pull request by alexevladgabriel**

### CODE REVIEW

**Comment by alexevladgabriel** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by RMartinOscar** [comment]
Hey react uses packages that are only available with yarn so you cannot replace it.
You can run yarn then use `pnpm import` but you need yarn anyway

**Comment by GeekCornerGH** [comment]
Hey @RMartinOscar I remember you x)

> Hey react uses packages that are only available with yarn so you cannot replace it. You can run yarn then use `pnpm import` but you need yarn anyway

Both yarn and pnpm are using the `npm` registry ([source for yarn](https://yarnpkg.com/getting-started/qa#why-registryyarnpkgcom-does-facebook-track-us), and [source for pnpm](https://pnpm.io/npmrc#registry)), meaning it won't affect the package availability. Hope it helps!

**Comment by lancepioch** [comment]
@alexevladgabriel Feel free to reopen this if you've made progress!

**Pull request closed without merging**
