### PR TITLE
Use database for notifications

### PR DESCRIPTION
**Pull request by notAreYouScared**
Adds a notification bell on top bar and  saves notification history. 

For future use in the front end, ex. Server crashes.

### CODE REVIEW

**Comment by RMartinOscar** [comment]
Hey i believe we can use `$panel->databaseNotifications()` in _AdminPanelProvider.php_ with [Filament 3](https://filamentphp.com/docs/3.x/panels/notifications) to avoid repetitiveness

**Comment by notAreYouScared** [comment]
> Hey i believe we can use `$panel->databaseNotifications()` in _AdminPanelProvider.php_ with [Filament 3](https://filamentphp.com/docs/3.x/panels/notifications) to avoid repetitiveness

We already use that. That's how you get the notification panel to appear at the top

**Review by lancepioch — CHANGES_REQUESTED** [review]
This basically duplicates the activity log. It should be consolidated.

**Review by Boy132 — COMMENTED** [review]
I agree with Lance. We should only send database notifications for "important" stuff. Sending both notifications for a simply success or error notifications seems unnecessary.

**Comment by notAreYouScared** [comment]
> This basically duplicates the activity log. It should be consolidated.

Are you referring to the client area activity log? This would rmsotly replace that when the new client area comes.

I still plan to keep activity logs per server.

Also there is no loy for the admin side.

**Pull request closed without merging**
