### PR TITLE
Add authentik oauth support

### PR DESCRIPTION
**Pull request by EkiciLP**
related to #385

### CODE REVIEW

**Comment by EkiciLP** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by EkiciLP** [comment]
related to #385

**Comment by RMartinOscar** [comment]
https://github.com/pelican-dev/panel/pull/435#issuecomment-2194608450
>Thanks but we'll add more providers once the oauth frontend is done. It will also be less hardcoded.

**Comment by Boy132** [comment]
Thank you for your contribution but the way how providers are added will be changed once we work on the oauth front end.
We will also add more default providers then.

**Pull request closed without merging**
