### PR TITLE
Update MariaDB EOL version for CI

### PR DESCRIPTION
**Pull request by lancepioch**

### CODE REVIEW

**Comment by Boy132** [comment]
10.3 was left on purpose beause that's our/ [Laravels minimum supported version](https://laravel.com/docs/11.x/database#introduction).

**Comment by lancepioch** [comment]
MariaDB 10.3 is end of life and not supported by MariaDB anymore.

**Comment by Boy132** [comment]
> MariaDB 10.3 is end of life and not supported by MariaDB anymore.

I know. We just need to be aware that this is raising our minimum supported mariadb version.

**Comment by lancepioch** [comment]
Yes, absolutely. We shouldn't be encouraging people to use outdated eol databases.

**Review by Boy132 — APPROVED** [review]

**Pull request merged**
