### PR TITLE
Installer: Shows errors on submit & move `runMigrations`

### PR DESCRIPTION
**Pull request by Boy132**
_Yet Another Installer PR._

Fixes errors on submit not showing because of `Halt` exception.
Moves the `runMigrations` call to submit to avoid cache problems.

### CODE REVIEW

**Review by RMartinOscar — CHANGES_REQUESTED** [review]
Errors are now shown but if any error occurs (like if redis is not reachable for a second when clicking finish) it will display
```
Migrations failed
SQLSTATE[HY000]: General error: 1 table "permissions" already exists (Connection: sqlite, SQL: create table "permissions" ("id" integer primary key autoincrement not null, "name" varchar not null, "guard_name" varchar not null, "created_at" datetime, "updated_at" datetime))
```
cause migrations already ran even though redis failed causing the finish step to never work

**Comment by Boy132** [comment]
> Errors are now shown but if any error occurs (like if redis is not reachable for a second when clicking finish) it will display
> 
> ```
> Migrations failed
> SQLSTATE[HY000]: General error: 1 table "permissions" already exists (Connection: sqlite, SQL: create table "permissions" ("id" integer primary key autoincrement not null, "name" varchar not null, "guard_name" varchar not null, "created_at" datetime, "updated_at" datetime))
> ```
> 
> cause migrations already ran even though redis failed causing the finish step to never work and you need to manually empty the database

Not sure if I understand you correctly, you got a redis error and that caused migrations to fail?

**Comment by notAreYouScared** [comment]
It should be noted that it creates a blank `database.sqlite` even if you change from sqlite

**Comment by Boy132** [comment]
> It should be noted that it creates a blank `database.sqlite` even if you change from sqlite
> 
> Edit: Image below, I got to the database screen, change the database name to `databa1se.sqlite` and it created both? but `database.sqlite` is a blank file. image

Can't reproduce that. Make sure you are on the right branch/ have the right files.

**Review by notAreYouScared — APPROVED** [review]
Looks good, Did notice that it no longer auto logins for you. Might just be a windows env thing.

**Pull request merged**
