### PR TITLE
Add exception handling to CreateNode/ EditNode & CreateServer/ EditServer

### PR DESCRIPTION
**Pull request by Boy132**
We probably want to add some more fine tuned exception handling at some point but for now this stops all 500 errors or silent errors and replaces them with a notification.

### CODE REVIEW

**Review by lancepioch — APPROVED** [review]
Looks good, I wonder if we should use traits for now?

**Comment by notAreYouScared** [comment]
I attempted to test this with editing a server but it caused the panel to lock up...

Edit Server -> Remove assigned user, click save.

**Comment by Boy132** [comment]
> I attempted to test this with editing a server but it caused the panel to lock up... image
> 
> Edit Server -> Remove Owner, click save.
> 
> This seems to break the stock error handling as the owner is a required field.

Yeah, seems like Filament doesn't like the livewire `exception` hook. I used good old try-catchs now.

**Comment by notAreYouScared** [comment]
Anyway we can catch the 500 on the create allocation, on the create server page? 

image
image
image


Unless we just need to rewrite the logic, the port already exists... we should just skip over it, and present an error saying something along the lines of

Failed to Create Allocation
Failed to Create: <IP>:<Port>, <error>

**Comment by Boy132** [comment]
> Anyway we can catch the 500 on the create allocation, on the create server page?
> 
> image image image
> 
> Unless we just need to rewrite the logic, the port already exists... we should just skip over it, and present an error saying something along the lines of
> 
> Failed to Create Allocation Failed to Create: :,

Wouldn't #395 fix/ change that anyways?

**Comment by notAreYouScared** [comment]
It would, but who knows when that would be done.

**Comment by notAreYouScared** [comment]
With latest changes 500's are still thrown when it skips the ports and does not return anything

image

**Review by lancepioch — CHANGES_REQUESTED** [review]
Memory leak

**Comment by notAreYouScared** [comment]
^^  Memory Leak when creating ports that **already** exist. 
image

**Comment by Boy132** [comment]
Closing this for now. Will look into that later, probably.

**Pull request closed without merging**
