### PR TITLE
adding arabic FIXED

### PR DESCRIPTION
**Pull request by Turkidev**

### CODE REVIEW

**Comment by Poseidon281** [comment]
I added it to the crowdin page: https://crowdin.com/project/pelican-panel/ar

I don't want to impose anything or anything, but I thought maybe it would be useful if I put it in my PR request and then add you to the credits.md to keep the overview for the admins

**Comment by Turkidev** [comment]
"Project does not exist or access to this project is limited"

**Comment by Poseidon281** [comment]
> "Project does not exist or access to this project is limited"

There is a new project: https://crowdin.com/project/pelican-dev

All of your translations have been uploaded into it and have been added to the repository by the developers

**Comment by Turkidev** [comment]
updated some files

**Comment by notAreYouScared** [comment]
Please us Crowdin

https://crowdin.com/project/pelican-dev

**Pull request closed without merging**
